# html lang
language: en

# main menu navigation
menu:
  文章: /article
  友链: /friendChain
  关于: /about

# stylesheets loaded in the <head>
stylesheets:
  - http://at.alicdn.com/t/c/font_4034228_1rpsrk0whsc.css
  - /weblog/css/reset.css
  - /weblog/css/layout.css
  - /weblog/css/index.css
  - /weblog/css/tag.css
  - /weblog/css/archive.css
  - /weblog/css/partials/recent-posts.css
  - /weblog/css/partials/personal-info.css
  - /weblog/css/partials/tag-list.css
  - /weblog/css/widgets/paginator.css

# scripts loaded in the end of the body
scripts:
  - /weblog/js/tools.js
  - /weblog/js/layout.js
