# html lang
language: en

# main menu navigation
menu:
  分类: /categories
  关于: /about
  计划: /todoList

# stylesheets loaded in the <head>
stylesheets:
  - http://at.alicdn.com/t/c/font_4034228_2j4kzmteu4l.css
  - /lib/prism/prism.css
  - /css/reset.css
  - /css/layout.css
  - /css/index.css
  - /css/tag.css
  - /css/archive.css
  - /css/post.css
  - /css/category.css
  - /css/partials/recent-posts.css
  - /css/partials/personal-info.css
  - /css/partials/tag-list.css
  - /css/partials/toc.css
  - /css/widgets/header.css
  - /css/widgets/paginator.css
  - /css/widgets/busuanzi.css
  - /css/widgets/twikoo.css
  - /css/helper/tag_list.css
  - /css/helper/menu_list.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.5.1.min.js
  - /lib/prism/prism.js
  - /js/tools.js
  - /js/layout.js
  - /js/busuanzi.pure.mini.js
  - http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# Loading Animation (加载动画)
preloader:
  enable: true

#  控制台打印信息
console:
  enable: true